# Generated by Django 4.2 on 2023-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0002_item_address_item_bedrooms_item_has_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('mansion', 'Mansion')], max_length=100),
        ),
    ]
